### PR TITLE
Fix icons size

### PR DESCRIPTION
**Pull request by avdata99**
Updated view

image

### CODE REVIEW

**Comment by chris48s** [comment]
The solution looks fine visually, but we shouldn't manually edit this file.

The source SCSS files for this project are in `./ckanext/unhcr/src/css` and then we compile them to `./ckanext/unhcr/fanstatic/theme.css` with grunt by running `make assets` (see https://github.com/okfn/ckanext-unhcr#building-static-assets ). Note this doesn't get done as part of the auto-reload in the dev container. You'll need to run `make assets` each time you change the source SCSS to see your changes.

Can you revert this, apply the relevant change to the source files then `theme.css` should be the compiled output. Ta

**Comment by avdata99** [comment]
> The solution looks fine visually, but we shouldn't manually edit this file.
> 
Done @chris48s

**Review by chris48s — APPROVED** [review]

**Comment by amercader** [comment]
This went to `ckan-2.9`, shouldn't we target `master` now?

**Comment by chris48s** [comment]
oh well spotted - sorry. Yes
I will cherry-pick the commit
@avdata99 for new PRs please submit them targetting master.

**Pull request merged**
