### PR TITLE
Kobo review

### PR DESCRIPTION
**Pull request by amercader**
WIP

### CODE REVIEW

**Comment by amercader** [comment]
@avdata99 Some more comments here:

* `special` is a really subjective term :) Let's use `kobo_type` in the [metadata](https://github.com/okfn/ckanext-unhcr/blob/c34c4a50e4122a3e26558913d651369bc65b6e82/ckanext/unhcr/kobo/kobo_dataset.py#L151) and `kobo-resources` in the templates / CSS (instead of `special-resources`)
* The design of the "Describe Kobo resources" page is a bit confusing, see comments below:
Screenshot 2021-08-17 at 16-02-05 Add data to the dataset - RIDL

    * Point 1: It should be made clear that these are automatically created resources, with a short paragraph saying "The following resources were automatically imported from Kobo. Please review and edit their metadata as necessary"
    * Point 2: I'd check with the client whether we want to allow adding extra resources at this stage (data or attachments) at all
    * Point 3: This should follow the same styling as the actions on the standard dataset form (ie a `btn-primary` button on the bottom right corner of the form
* Once you are editing one of the automatically created resources, the buttons on the form don't make sense, and clicking on "Finish" will actually publish the dataset. It should say "Update" and redirect back to the "Describe Kobo resources" page above (ie it should keep the dataset as a draft):

Screenshot 2021-08-17 at 16-13-30 Add data to the dataset - RIDL

**Review by avdata99 — APPROVED** [review]

**Comment by avdata99** [comment]
`special` to `kobo_type` and CSS classes renamed [here](https://github.com/okfn/ckanext-unhcr/pull/667/commits/0493d749d5bdf99a8421b1c4f99a8c20804d7acb)

**Comment by avdata99** [comment]
1 and 3, ready.
Also buttons at the bottom.

**Comment by avdata99** [comment]
With [this](https://github.com/okfn/ckanext-unhcr/pull/667/commits/79bcecdc6d916efac5decad4f2ccd7f314e1caba), we are now able to edit a auto-kobo resource and back to the new resource form

Without the `<input type="hidden" value="{{ data.kobo_type }}" name="kobo_type" />` we loose this field after updating an automatic KoBo resource

Should we add `kobo_type` as a field in the resources schema @amercader?

**Comment by amercader** [comment]
> Should we add kobo_type as a field in the resources schema @amercader?
@avdata99 If needed yes, but it should not be mandatory to be backwards compatible, ie no use of `resource['kobo_type']`, but rather `resource.get('kobo_type')`

**Comment by amercader** [comment]
@avdata99 The changes help but this page is still too confusing. Here's where we I think we should head to:

Screenshot 2021-08-18 at 12-47-37 Add data to the dataset - RIDL

The top half shows automatically created Kobo resources. The mockup uses the standard `package/snippets/resources_list.html` snippet but we should use a custom one specific for Kobo resources in this page that:
* Displays all metadata fields like you have now on the `survey_data.html` and `survey_questionnaire.html` (adapted to the new row based style)
* Only displays an edit button (perhaps with `btn-default` instead of `btn-primary`) instead of the dropdown

I personally think that the second half (Additional resources) should be completely removed from this stage to simplify the workflow (and our code). If we keep it let's rename the button from "Update Kobo Resource" to "Add additional resource".

The third and missing part is the bottom half, where the "Publish" button should be. This should be the standard `form-actions` div like eg in the dataset form:
Screenshot 2021-08-18 at 13-01-09 Dataset - RIDL

I'm not sure why this does not currently come up . It might be because of the [JS module](https://github.com/okfn/ckanext-unhcr/blob/master/ckanext/unhcr/src/js/module-resource-type.js) (called from [this field](https://github.com/okfn/ckanext-unhcr/blob/master/ckanext/unhcr/templates/scheming/form_snippets/resource_type.html#L1)) that hides/shows all the data/attachment fields or because of template block logic.

Let me know if all this makes sense. I think overall the changes make for a more intuitive workflow

**Comment by amercader** [comment]
@avdata99 sorry forgot to paste the diff for the mockup above based on the latest `kobo-review` branch:

```diff
diff --git a/ckanext/unhcr/templates/scheming/package/snippets/resource_form.html b/ckanext/unhcr/templates/scheming/package/snippets/resource_form.html
index 13405e2..08217a3 100644
--- a/ckanext/unhcr/templates/scheming/package/snippets/resource_form.html
+++ b/ckanext/unhcr/templates/scheming/package/snippets/resource_form.html
@@ -16,36 +16,23 @@
 
   {% if draft_kobo_resource and new_kobo_resource %}
 
+  <h1>KoBo resources</h1>
+
     {# We are just after a new KoBo package is created. We are not editing a resource #}
 
   <div class="kobo-resources-container">
-    <h3>The following resources were automatically imported from Kobo. 
-        Please review and edit their metadata as necessary</h3>
-    {# show all special kobo resources #}
-    {% for resource in pkg_dict.resources %}
-    
-      {% set is_data = resource.kobo_type == 'data' %}
-      {% set is_questionnaire = resource.kobo_type == 'questionnaire' %}
-      {% if is_data %}
-        {{ h.snippet('package/snippets/survey_data.html', resource=resource) }}
-      {% elif is_questionnaire %}
-        {{ h.snippet('package/snippets/survey_questionnaire.html', resource=resource) }}
-      {% endif %}
-    {% endfor %}
+    <p>The following resources were automatically imported from Kobo.
+        Please review and edit their metadata as necessary</p>
 
-    <div class="kobo-resources-publish">
-      <b>If the resources are ready you can</b>
-      <a
-        href="{% url_for 'unhcr_dataset.publish', dataset_id=pkg_dict.id %}"
-        class="btn btn-primary">
-          {{ _('Publish Dataset') }}
-      </a>
-    </div>
-    
-  </div>
+    {# TODO: Use customized Kobo specific snippets #}
+    {% snippet "package/snippets/resources_list.html", pkg=pkg_dict, type='data' %}
+    {% snippet "package/snippets/resources_list.html", pkg=pkg_dict, type='attachment' %}
+
+
+  <h1>Additional resources</h1>
+
+  <p>You can optionally add additional resources to the dataset. This can also be done later.</p>
 
-  <h2>Or you can add more resources</h2>
-  
 {% endif %}
 
 {% endblock %}
```

**Comment by avdata99** [comment]
Patch applyed [here](https://github.com/okfn/ckanext-unhcr/commit/244f418037a3e5593341764bcc9729e183f5560b) @amercader 
I will continue by adding a custom `resource_list` snippet

**Comment by avdata99** [comment]
Custom snippets for KoBo resources [here](https://github.com/okfn/ckanext-unhcr/pull/667/commits/156acf7e27103fcab1872326907c7fa5ac98f5c5) @amercader 

Selection_339

**Comment by avdata99** [comment]
Schema for KoBo resources updated to include `kobo_type` and `kobo_details` (dict) [here](https://github.com/okfn/ckanext-unhcr/pull/667/commits/118545ffec7e0a261f887ecb4d6088220ab78d6a).

**Comment by amercader** [comment]
@avdata99 I pushed a some change to make the page more readable and aligned with the rest of the site design
Screenshot 2021-08-19 at 12-05-47 Add data to the dataset - RIDL

**Pull request merged**
