### PR TITLE
Fixed data-container facet urls

### LINKED ISSUE #99: Remove facet links use organization url instead of data-container
# Overview

Screenshot from 2019-03-28 11-37-37

### PR DESCRIPTION
**Pull request by roll**
- fixes #99

### CODE REVIEW

**Comment by roll** [comment]
@amercader 
Have you tried? I works for pills for me. Probably because it changes the base url

**Comment by amercader** [comment]
@roll yes, on this branch pills don't work for me:

Screenshot from 2019-05-22 13-14-54

But the close buttons on the facet list do:

Screenshot from 2019-05-22 13-15-17

**Comment by roll** [comment]
I was wrong.. It doesn't work

**Comment by roll** [comment]
@amercader 
Regarding the org facet removal - https://github.com/okfn/ckanext-unhcr/issues/163

**Pull request merged**
