### PR TITLE
Fix reset password for external users

### LINKED ISSUE #852: Error 500 recovering user
Error 500 trying to recover a password

<pre>
2022-07-05T09:37:28.330-03:00 | 2022-07-05 12:37:28,330 ERROR [ckan.config.middleware.flask_app] Action user_show requires an authenticated user
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/lib/python3.8/site-packages/flask/views.py", line 89, in view
return self.dispatch_request(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/flask/views.py", line 163, in dispatch_request
return meth(*args, **kwargs)
File "/srv/app/src/ckan/ckan/config/middleware/../../views/user.py", line 741, in get
context, user_dict = self._prepare(id)
File "/srv/app/src/ckan/ckan/config/middleware/../../views/user.py", line 681, in _prepare
user_dict = logic.get_action(u'user_show')(context, {u'id': id})
File "/srv/app/src/ckan/ckan/logic/__init__.py", line 504, in wrapped
result = _action(context, data_dict, **kw)
File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/actions.py", line 1549, in user_show
user = up_func(context, data_dict)
File "/srv/app/src/ckan/ckan/logic/action/get.py", line 1413, in user_show
_check_access('user_show', context, data_dict)
File "/srv/app/src/ckan/ckan/logic/__init__.py", line 313, in check_access
raise NotAuthorized(msg)
ckan.logic.NotAuthorized: Action user_show requires an authenticated user

<b>[ckan.config.middleware.flask_app] 500 /user/reset/XX render time 0.031 seconds</b>
</pre>

### PR DESCRIPTION
**Pull request by avdata99**
Fixes #852 

Probably this hasn't worked for a long time

Problems:
 - CKAN generates a reset URL with the `user_id` and we use `User.by_name` to validate any auth function.
 - `user_reset` it's not an allowed action
 - `user_show` is not allowed for anonymous access.

### CODE REVIEW

**Comment by avdata99** [comment]
@amercader, `user_reset` includes an anonymous* call to `user_show` [here](https://github.com/ckan/ckan/blob/master/ckan/views/user.py#L676-L684)

```python
try:
    logic.check_access(u'user_reset', context)
except logic.NotAuthorized:
    base.abort(403, _(u'Unauthorized to reset password.'))

try:
    user_dict = logic.get_action(u'user_show')(context, {u'id': id})
except logic.NotFound:
     base.abort(404, _(u'User not found'))
```

* Required a `auth_user_obj` [here](https://github.com/ckan/ckan/blob/master/ckan/authz.py#L233-L234)

I think we need this, fix test and ensure we hide `user_show` to public user in a different way.

**Comment by amercader** [comment]
@avdata99 I had a quick try locally and after removing `@toolkit.auth_allow_anonymous_access`  the reset process seemed to work properly, can you double check if it is actually needed?
Also the flask messages are not showing up after redirecting to the home page (it appears eg if you click on a login page)

**Comment by avdata99** [comment]
@amercader if I remove the `@toolkit.auth_allow_anonymous_access` from the `user_show` auth fn, I get

image

If I leave the decorator, it works fine.
We are not really allowing anonymous users to see users profile. 
The `user_show` auth function was created to ensure external users only are able to show their own profile.
If no user is logged in, the auth function will return an error.
In this case, we allow only and extra check, the `context['user_obj']`
But if no user is logged in, any `/user/USER_NAME_OR_ID` URL will work.
Maybe it's fine to add the decorator.

I'll check the flash messages, something is not working.

**Comment by avdata99** [comment]
To review test error

<pre>
        with pytest.raises(toolkit.NotAuthorized):
            helpers.call_action(
                'user_show',
                context=context,
                id=user['id']
            )
<b>Failed: DID NOT RAISE <class 'ckan.logic.NotAuthorized'></b>
</pre>

**Comment by amercader** [comment]
Fair enough @avdata99 , sorry for being a bit paranoid. go ahead with the decorator and the changes in `user_show` (plus the flash messages and tests fixing)

**Comment by avdata99** [comment]
@amercader I just added an [extra security layer with a context value](https://github.com/okfn/ckanext-unhcr/pull/853/commits/89b04078ffc7aef93ae6d0caf307384c974dfc33).
I think is good enough.
I also had some troubles with the `site_read` permission so I allow some endpoints [here](https://github.com/okfn/ckanext-unhcr/pull/853/commits/d180cb3ae7e3f4659e103b93239ffe30eece5479)
I'll check the flash messages

**Comment by avdata99** [comment]
About flash messages, we are missing them on our home page.
We changed that [~2 years ago](https://github.com/okfn/ckanext-unhcr/commit/5d08e19e0dee41d73f5c8cdcfa9b4c29b3cdfc12)

We can recover them with [this](https://github.com/okfn/ckanext-unhcr/commit/142c1d749025a99485c0b513bdcb88fb0f88149d)

image

**Review by amercader — APPROVED** [review]

**Pull request merged**
